version: "3.9"
services:
  proxy:
    container_name: proxy
    build:
      context: ./.docker/proxy
      args:
        ENABLED_MODULES: brotli headers-more modsecurity
    environment:
      - NGINX_HOSTNAME=
      - EMAIL_LETSENCRYPT=
    volumes:
      - ./.docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/proxy/templates:/etc/nginx/templates:ro
      - certbot_data:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./.docker/web/Dockerfile
    env_file:
      - .web.env
    restart: unless-stopped

volumes:
  certbot_data:
