services:
  proxy:
    container_name: proxy
    build:
      context: ./.docker/proxy
    environment:
      - SERVER_NAME=
      - PROXIED_SERVER=
      - PROXIED_PORT=
    volumes:
      - ./.docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/proxy/templates:/etc/nginx/templates:ro
      - ssl:/etc/nginx/ssl:ro
    ports:
      - "80:8080"
      - "443:8443"
    restart: unless-stopped
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: ./.docker/web/Dockerfile
    environment:
      - TOPIC=
    restart: unless-stopped

volumes:
  ssl:
