services:
  proxy:
    container_name: proxy
    build:
      context: ./.docker/proxy
      args:
        ENABLED_MODULES: brotli headers-more modsecurity
    environment:
      - SERVER_NAME=
      - PROXIED_SERVER=
    volumes:
      - ./.docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/proxy/templates:/etc/nginx/templates:ro
      - ssl:/etc/nginx/ssl:ro
    ports:
      - "80:8080"
      - "443:8443"
    restart: unless-stopped
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./.docker/web/Dockerfile
    env_file:
      - .web.env
    restart: unless-stopped

volumes:
  ssl:
