name: "Lint"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint code
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          JAVASCRIPT_DEFAULT_STYLE: prettier
          CSS_FILE_NAME: .stylelintrc.js
