// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/contact.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/button.tsx";
import * as $$1 from "./islands/contact_form.tsx";
import * as $$2 from "./islands/navbar_burger.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/contact.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/button.tsx": $$0,
    "./islands/contact_form.tsx": $$1,
    "./islands/navbar_burger.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
